services:
  - type: web
    name: royal-industries
    env: php
    buildCommand: |
      composer install
      php artisan storage:link || true
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
